namespace Subverted.Cli;

public static class HelpText
{
    public static IReadOnlyList<string> Lines { get; } =
    [
        "sv — a Subversion client that does not feel like a punishment.",
        string.Empty,
        "  sv st [PATH...]         what has changed, from the daemon's warm index",
        "    -v, --verbose         include nodes with nothing to report, and revisions",
        "    --no-ignore           include ignored nodes",
        "  sv log [PATH]           revision history, newest first",
        "    -l, --limit N         how many revisions (default 20)",
        "    --all                 the whole history, however long it takes",
        "  sv d [PATH]             local changes as a unified diff",
        "  sv up [PATH]            bring the rest of the studio's work in",
        "  sv add PATH...          schedule paths for addition",
        "  sv commit [PATH...]     send changes under these paths to the server",
        "    -m, --message TEXT    the log message (required)",
        "    --mark                also record what the disk says happened: add new (?) files,",
        "                          delete missing (!) ones, keep hand-renames as moves",
        "  sv pick [PATH]          go through the changes one at a time and commit what you pick;",
        "                          y on a ?, ! or rename adds, deletes or moves it on the way",
        "    -m, --message TEXT    the log message (required)",
        "  sv lock PATH...         take the lock on files nothing can merge, before you edit them",
        "    -m, --message TEXT    what the lock is for, shown to whoever else tries",
        "    --steal               take a lock somebody else is holding",
        "  sv unlock PATH...       give the lock back",
        "    --break               release a lock somebody else is holding",
        "  sv resolve PATH...      mark conflicts settled, once you have decided which side wins",
        "    --working             the files as they are on disk — use after fixing the merge",
        "    --mine                this working copy's version, whole",
        "    --theirs              the incoming version, whole — asks first",
        "    --base                the revision both sides started from — asks first",
        "    -y, --yes             do not ask",
        "  sv revert PATH...       throw local changes away — lists them and asks first",
        "    -y, --yes             do not ask",
        "  sv rm PATH...           take files out of SVN and off disk — lists them and asks first",
        "    -y, --yes             do not ask",
        "  sv mv OLD NEW           rename a node, keeping its history — works after the fact too,",
        "                          when the rename was already made in a file manager",
        "  sv cleanup [PATH]       unstick a working copy a crashed client left locked (L)",
        "    -y, --yes             do not ask",
        "  sv daemon status        what the daemon is holding and whether it is watching",
        "  sv daemon stop          shut the daemon down",
        "  sv --version",
        string.Empty,
        "  --no-color              never emit ANSI colour",
        "  --no-pager              never page, however long the listing is",
        "  --timing                say where the time went, daemon share separately",
        string.Empty,
        "The daemon starts itself on first use. `svn` keeps working in the same folder —",
        "and everything but `sv st` shells out to it, so it has to be on PATH.",
    ];
}
